### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-singleton-frazer-fondacci-singleton#1]
- non terminé

**Comment by hartyshow** [comment]
On a presque terminé le projet mais nous avons un problème : lors de la l'exécution, une erreur s'affiche en console : 
A component required a bean of type 'loggable.Person' that could not be found.

Savez-vous d'où cela peut venir ? J'ai pourtant l'impression que tout est bien annoté.

**Comment by Slashgear** [comment]
- [] La définition d'un bean n'est pas correcte.
- [] pour votre souci, de quel partie du tp parlez vous?

**Comment by hartyshow** [comment]
J'ai modifié la définition d'un bean.

**Comment by hartyshow** [comment]
Il s'agit de la dernière partie du TP, concernant Spring boot

**Comment by hartyshow** [comment]
Il me semble pas avoir vu le bean dans le context. Certaines annotations manquent ?

**Comment by Slashgear** [comment]
En regardant il me semble pas qu'il en manque. Je pense pas que ce soit ça mais quand tu mets une annotation sans paramètre, évite les parenthèses. `@MonAnnotation` au lieu de `MonAnnotation()`

**Comment by hartyshow** [comment]
J'ai modifié pour l'annotation mais comme vous disiez, le problème ne vient pas de là.

**Comment by hartyshow** [comment]
Ah je crois avoir trouvé et corrigé le problème, j'ai ajouté scanBasePackages={"Cat", "Person", "Loggable"} dans l'annotation @SpringBootApplication de mon main et ça fonctionne désormais !

**Comment by Slashgear** [comment]
Tu aurais pu remonter ta classe de configuration d'un niveau dans l'arborescence. Mais en effet, sans ça, l'appli ne chargeait pas les packages.
